EDUCATION_KEYWORDS = [
    "Bachelor",
    "B.Tech",
    "B.E",
    "B.Sc",
    "M.Tech",
    "M.E",
    "M.Sc",
    "MBA",
    "PhD",
    "Diploma",
    "Intermediate",
    "Higher Secondary",
    "High School",
    "Secondary School",
    "University",
    "College",
    "Institute",
    "School",
]
