ROLE_KEYWORDS = [
    "software engineer",
    "software developer",
    "frontend developer",
    "backend developer",
    "full stack developer",
    "web developer",
    "android developer",
    "ios developer",
    "python developer",
    "java developer",
    "intern",
    "internship",
    "research intern",
    "machine learning engineer",
    "ai engineer",
    "data analyst",
    "data scientist",
    "graduate engineer trainee",
    "associate engineer",
]

COMPANY_KEYWORDS = [
    "technologies",
    "technology",
    "solutions",
    "systems",
    "labs",
    "private limited",
    "pvt ltd",
    "limited",
    "inc",
    "llc",
    "llp",
    "corporation",
    "company",
]