TECHNICAL_SKILLS = [
    # Programming Languages
    "Python",
    "Java",
    "C",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Kotlin",
    "Swift",
    # Frontend
    "HTML",
    "CSS",
    "React",
    "Next.js",
    "Redux",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Vue",
    "Angular",
    # Backend
    "Node.js",
    "Express",
    "FastAPI",
    "Django",
    "Flask",
    "Spring Boot",
    # Databases
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Redis",
    "Firebase",
    # AI / ML
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "NLP",
    "OpenCV",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "spaCy",
    # Cloud
    "AWS",
    "Azure",
    "Google Cloud",
    # DevOps
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "CI/CD",
    # APIs
    "REST API",
    "GraphQL",
    # Other
    "Linux",
    "Postman",
    "Figma",
    "Solidity",
    "Web3",
    "Ethereum",
    "JWT",
]
