PROJECT_TITLE_KEYWORDS = [
    "project",
    "projects",
    "academic project",
    "personal project",
    "major project",
    "minor project",
    "capstone project",
]

TECHNOLOGY_HINTS = [
    "react",
    "reactjs",
    "react.js",
    "node",
    "nodejs",
    "node.js",
    "express",
    "expressjs",
    "mongodb",
    "mysql",
    "postgresql",
    "firebase",
    "python",
    "java",
    "c++",
    "javascript",
    "typescript",
    "html",
    "css",
    "tailwind",
    "bootstrap",
    "fastapi",
    "django",
    "flask",
    "spring",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "redis",
]
